name: chickenline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.0.0-beta.18
  mime: ^1.0.5
  http: ^1.2.1
  package_info_plus: ^8.3.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  appsflyer_sdk: ^6.11.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.3.2
  provider: ^6.1.2
  flutter_riverpod: ^2.4.0


  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/unity/
    - assets/unity/index.html
    - assets/unity/Build/Builds.loader.js
    - assets/unity/TemplateData/style.css
    - assets/unity/Build/Builds.data
    - assets/unity/Build/Builds.framework.js
    - assets/unity/Build/Builds.wasm
    - assets/unity/TemplateData/unity-logo-dark.png
    - assets/unity/TemplateData/progress-bar-empty-dark.png
    - assets/unity/TemplateData/progress-bar-full-dark.png